# Site settings
title: Kode with Kelsey
header-img: img/home-bg.png
email: kfecho30@gmail.com
copyright_name: kfecho30
description: > # this means to ignore newlines until "baseurl:"
  A Learn-Along
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kfecho30
learn_profile: kfecho30
email_username: kfecho30@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
